version: '3.9'

services:
    postgres:
        image: postgres
        container_name: postgres_container
        restart: on-failure
        environment: 
            - POSTGRES_DB=flower
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=admin
        networks: 
            - main
        ports: 
            - "5432:5432"
        volumes: 
            - ./data/postgres:/var/lib/postgresql/data 


    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin
        restart: on-failure
        environment:
            - PGADMIN_DEFAULT_EMAIL=root@root.com
            - PGADMIN_DEFAULT_PASSWORD=root
        ports:
            - "5050:80"
        volumes:
            - ./data/pgadmin:/var/lib/pgadmin/data
        networks:
            - main
    
    app:
        container_name: app
        build: .
        command: sh -c "python3 manage.py makemigrations && 
                        python3 manage.py migrate && 
                        python3 manage.py collectstatic --no-input && 
                        python3 manage.py initadmin && 
                        gunicorn -k gevent flower.wsgi:application -b 0.0.0.0:8000"
        restart: on-failure
        depends_on: 
            - postgres
        expose: 
            - "8000"
        networks:
            - main
        volumes: 
            - .:/code/
            - ./static:/app/static
            - ./media:/app/media

        
    nginx:
        container_name: nginx
        command: nginx -g 'daemon off;'
        image: nginx
        restart: on-failure
        depends_on:
            - app
        networks: 
            - main
        ports: 
            - "80:80"
        volumes: 
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./media:/app/media
            - ./static:/app/static


networks: 
    main:
        external: true

volumes: 
    static:
        external: true
    media:
        external: true
    data:
        external: true
